//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_RACKET                      131
#define IDB_BACKGROUND                  132
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDC_GAMECURSOR                  153
#define IDB_LOADING                     156
#define cat                             166
#define cat2                            172
#define cat3                            173
#define cat_punch                       174
#define cat_attack                      175
#define cat_attack2                     176
#define cat_attack3                     177
#define dog                             178
#define dog2                            179
#define dog3                            181
#define dog_punch                       182
#define dog_attack                      183
#define dog_attack2                     186
#define dog_attack3                     187
#define IDB_MAP                         191
#define die2                            197
#define die3                            198
#define die4                            199
#define die1                            200
#define cat_base                        201
#define dog_base                        202
#define basic_cat_btn                   205
#define SLASH                           206
#define basic_cat_btn_dark              207
#define WON                             208
#define tank_cat                        209
#define tank_cat2                       210
#define tank_cat3                       211
#define tank_cat_attack                 212
#define tank_cat_attack2                213
#define tank_cat_attack3                214
#define tank_cat_btn                    215
#define tank_cat_attack4                216
#define tank_cat_punch                  217
#define tank_cat_btn_dark               218
#define zero                            219
#define one                             220
#define two                             222
#define three                           223
#define four                            224
#define five                            225
#define six                             226
#define seven                           227
#define eight                           228
#define nine                            229
#define SLASH2                          230
#define L0                              231
#define L1                              233
#define L2                              234
#define L3                              235
#define L4                              237
#define L5                              238
#define L6                              239
#define L7                              240
#define L8                              241
#define L9                              242
#define LW                              243
#define level1                          244
#define level1_2                        245
#define level1_dark                     246
#define level2                          247
#define level2_2                        248
#define level2_dark                     249
#define level3                          250
#define level3_2                        251
#define level3_dark                     252
#define level4                          253
#define level4_2                        254
#define level4_dark                     255
#define level5                          256
#define level5_2                        257
#define level5_dark                     258
#define level6                          259
#define level6_2                        260
#define level6_dark                     261
#define level7                          262
#define level7_2                        263
#define level7_dark                     264
#define level8                          265
#define Start                           266
#define long_leg_cat_btn                271
#define long_leg_cat_btn_dark           275
#define long_leg_cat                    276
#define long_leg_cat2                   277
#define long_leg_cat3                   278
#define long_leg_cat4                   279
#define long_leg_cat5                   283
#define long_leg_cat6                   284
#define long_leg_cat_attack             285
#define long_leg_cat_attack2            287
#define long_leg_cat_attack3            288
#define long_leg_cat_attack4            289
#define long_leg_cat_punch              290
#define long_leg_cat_attack1            291
#define battle_cat                      292
#define battle_cat2                     293
#define battle_cat3                     294
#define battle_cat_attack               296
#define battle_cat_attack2              297
#define battle_cat_attack3              298
#define battle_cat_attack4              299
#define battle_cat_punch                300
#define battle_cat_btn                  301
#define battle_cat_btn_dark             302
#define world_map                       303
#define start_btn                       306
#define start_btn2                      307
#define start_btn3                      308
#define start_btn4                      309
#define return_btn                      314
#define return_btn2                     315
#define return_btn3                     316
#define return_btn4                     317
#define return_btn5                     318
#define IDB_BITMAP1                     319
#define start_btn5                      319
#define God_cat                         320
#define IDB_BITMAP2                     321
#define God_cat_bg                      321
#define God_cat_01                      322
#define God_cat_02                      323
#define God_cat_03                      324
#define God_cat_04                      325
#define God_cat_05                      326
#define God_cat_06                      327
#define God_cat_07                      328
#define God_cat_08                      329
#define God_cat_09                      330
#define God_cat_10                      331
#define God_cat_11                      332
#define God_cat_12                      333
#define God_cat_13                      334
#define God_cat_14                      335
#define God_cat_15                      336
#define God_cat_16                      337
#define God_cat_17                      338
#define God_cat_18                      339
#define God_cat_19                      340
#define God_cat_20                      341
#define God_cat_21                      342
#define God_cat_22                      343
#define God_cat_23                      344
#define God_cat_24                      345
#define God_cat_25                      346
#define God_cat_26                      347
#define God_cat_27                      348
#define God_cat_28                      349
#define God_cat_29                      350
#define God_cat_30                      351
#define God_cat_31                      352
#define God_cat_32                      353
#define God_cat_33                      354
#define God_cat_34                      355
#define God_cat_35                      356
#define God_cat_36                      357
#define God_cat_37                      358
#define God_cat_38                      359
#define God_cat_39                      360
#define God_cat_40                      361
#define God_cat_41                      362
#define God_cat_42                      363
#define God_cat_43                      364
#define God_cat_44                      365
#define God_power                       366
#define God_catR                        367
#define God_choose                      367
#define God_left                        368
#define God_leftM                       369
#define BlingL                          371
#define BlingL_01                       372
#define BlingL_02                       373
#define BlingL_03                       374
#define BlingL_04                       375
#define BlingL_05                       376
#define BlingL_06                       377
#define BlingL_07                       378
#define BlingL_08                       379
#define BlingL_09                       380
#define BlingL_10                       381
#define BlingL_11                       382
#define BlingL_12                       383
#define BlingL_13                       384
#define BlingL_14                       385
#define BlingL_15                       386
#define BlingL_16                       387
#define BlingL_17                       388
#define BlingL_18                       389
#define BlingL_19                       390
#define BlingL_20                       391
#define BlingL_21                       392
#define BlingL_22                       393
#define BlingL_23                       394
#define BlingL_24                       395
#define IDB_BITMAP3                     396
#define BlingL_25                       396
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        397
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
